import {
  Activity,
  AlertCircle,
  Archive,
  ArrowRight,
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleDot,
  CirclePause,
  Database,
  FileSearch,
  FileText,
  Filter,
  FlaskConical,
  Folder,
  GraduationCap,
  Hand,
  HeartHandshake,
  Inbox,
  KeyRound,
  Layers3,
  Leaf,
  ListFilter,
  ListTree,
  LoaderCircle,
  LockKeyhole,
  Mail,
  Menu,
  MessageSquareText,
  MonitorUp,
  Network,
  PackageCheck,
  PanelsTopLeft,
  Pause,
  Play,
  RefreshCw,
  Route,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Store,
  Tag,
  TerminalSquare,
  Trash2,
  UserRound,
  Waypoints,
  Workflow,
  X,
  XCircle,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  alert: AlertCircle,
  archive: Archive,
  arrowRight: ArrowRight,
  chart: BarChart3,
  book: BookOpen,
  bot: Bot,
  boxes: Boxes,
  briefcase: BriefcaseBusiness,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  circleDot: CircleDot,
  corpus: Database,
  database: Database,
  domains: PanelsTopLeft,
  error: XCircle,
  filter: Filter,
  file: FileText,
  flask: FlaskConical,
  folder: Folder,
  handoff: Hand,
  heart: HeartHandshake,
  inbox: Inbox,
  key: KeyRound,
  layers: Layers3,
  learning: GraduationCap,
  leaf: Leaf,
  listFilter: ListFilter,
  listTree: ListTree,
  loading: LoaderCircle,
  lock: LockKeyhole,
  mail: Mail,
  menu: Menu,
  message: MessageSquareText,
  monitor: MonitorUp,
  network: Network,
  overview: PanelsTopLeft,
  package: PackageCheck,
  pause: Pause,
  paused: CirclePause,
  play: Play,
  refresh: RefreshCw,
  route: Route,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  store: Store,
  tag: Tag,
  terminal: TerminalSquare,
  trash: Trash2,
  user: UserRound,
  waypoints: Waypoints,
  workflow: Workflow,
  inspect: FileSearch,
  close: X,
};

const DOMAIN_ICONS = {
  career_search: BriefcaseBusiness,
  facebook_marketplace: Store,
  indeed_jobs: Search,
  workday: Workflow,
  greenhouse: Leaf,
  linkedin_jobs: Network,
  gmail: Mail,
  shopify: Store,
  google: Layers3,
};

export function AppIcon({ name, size = 18, strokeWidth = 1.8, className = "", ...props }) {
  const Icon = ICONS[name] || Circle;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} {...props} />;
}

export function DomainIcon({ id, size = 18, className = "", ...props }) {
  const Icon = DOMAIN_ICONS[id] || Boxes;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={1.8} {...props} />;
}
