"""The SEMANTIC layer: a canonical answer -> THIS widget's vocabulary.

    The store is canonical. Every widget has its own vocabulary. Sometimes the question's
    polarity inverts.

The answer store says `education_degree = "Bachelor of Science"`. The widget offers
"Bachelor's Degree". Nothing in the Interaction API can bridge that: `/select_option` takes
the word the widget uses, and the store holds the word the human uses. This module is the
translator, and it is the one place in the stack where REASONING (not matching) is required.

--------------------------------------------------------------------------------------
The cascade — cheapest-first, the project's existing doctrine applied here
--------------------------------------------------------------------------------------
    1. exact        free      "Mobile" -> Mobile
    2. normalised   free      "Bachelor of Science" -> "Bachelor's Degree" (case/punct/plural)
    3. alias        free      Sports Science -> Kinesiology   (apply_fields, operator-editable)
    4. model        ~$0.002   question + options + canonical -> one option, or NONE
    5. none         one-time  ask the operator, then write the answer back into rung 3

Rung 4 is a SEAM, not an implementation: `resolve_answer(..., model=fn)`. `fn` takes a
`SemanticQuestion` and returns a `ModelAnswer`. That signature is the whole point of this
module — it is what a LOCAL model will implement once it is trained, and what a bounded
Haiku call implements in the meantime. Neither is wired here, because the rung that needs a
model should not be faked by one that doesn't have one: with no `model` the cascade returns
`none` + `needs_human`, which is honest and is rung 5.

--------------------------------------------------------------------------------------
Why the polarity guard comes BEFORE the free rungs, and not after
--------------------------------------------------------------------------------------
This is the load-bearing idea, and it inverts the obvious design. The obvious cascade tries
the free rungs first and escalates on a miss. That is WRONG for an inverted question, because
the free rungs do not miss — they HIT, confidently, and produce the opposite of the truth:

    store: ai_use_attestation = "Yes"   (meaning: I did not use AI)
    KKR:   "I confirm my materials were NOT generated by AI"  -> Yes = confirming.  Yes is right.
    other: "Did you use AI tools in this application?"        -> Yes = admitting.   Yes is WRONG.

Same store value, same options `["Yes", "No"]`, opposite correct answers. An exact match on
"Yes" succeeds in both cases and is silently wrong in one. **Matching options without reading
the question inverts a real answer** (docs/PLAN_interaction_api.md §5.1), and no amount of
better matching fixes it — the information needed is in the QUESTION, which rungs 1-3 never
read. So polarity is checked first, and when it is at risk the free rungs are SKIPPED
entirely and the question goes to a reasoner. That is the sharpest case for a model over a
regex anywhere in this system, and it is why this module exists before the model does.

Guardrails (PLAN §5): confidence threshold -> ask, don't guess. Never invent application
content. Log `rationale` so a wrong alias is auditable rather than mysterious.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from typing import Callable, Optional, Protocol

import apply_fields
from apply_recipe import is_ai_use_attestation

#: Below this, the caller asks the operator rather than filling. Rungs 1-3 are deterministic
#: and score 1.0; only a model returns anything else.
CONFIDENCE_THRESHOLD = 0.75


@dataclass(frozen=True)
class SemanticQuestion:
    """The payload a reasoner receives. Everything it needs, nothing it doesn't.

    THIS IS THE LOCAL MODEL'S INPUT CONTRACT. Keep it small and stable: it is a prompt
    surface today and a training feature set tomorrow, and every field added here is a field
    a distilled model must learn to use. Note it carries the QUESTION — the thing rungs 1-3
    are structurally unable to read, and the reason this rung exists at all.
    """

    question_text: str
    options: tuple[str, ...]
    canonical_answer: str
    ats: Optional[str] = None
    field: Optional[str] = None
    #: True when matching options without reading the question could invert the answer.
    polarity_risk: bool = False
    #: Why the cheap rungs did not answer — the reasoner's brief.
    why: str = ""


@dataclass(frozen=True)
class ModelAnswer:
    """What a reasoner returns. `value=None` means NONE — the honest answer when no offered
    option is right (University of Santo Tomas simply is not in Greenhouse's list)."""

    value: Optional[str]
    confidence: float
    rationale: str = ""


class Reasoner(Protocol):
    """Rung 4. A local model, a bounded Haiku call, or a test double — same shape.

    Implementations MUST be allowed to answer NONE. A reasoner that always picks something
    is a plausible-guess generator, which is worse than an escalation: "never invent
    application content" (PLAN §5).
    """

    def __call__(self, q: SemanticQuestion) -> Optional[ModelAnswer]: ...


@dataclass(frozen=True)
class Resolution:
    """The cascade's verdict."""

    value: Optional[str]
    confidence: float
    method: str          # exact | normalised | alias | model | none
    rationale: str
    needs_human: bool

    @property
    def ok(self) -> bool:
        return self.value is not None and not self.needs_human


# --- normalisation ------------------------------------------------------------------
#: Apostrophes are DELETED, not spaced — the rest of the punctuation is spaced.
#: "Bachelor's" must normalise to "bachelors" (-> "bachelor"), not to "bachelor s", or it
#: fails to match a stored "Bachelors Degree" written without the apostrophe: the stray "s"
#: survives as its own token while the plural "s" gets singularised away. Covers the straight
#: quote, the curly one Greenhouse renders (U+2019), and the modifier letter (U+02BC).
_APOS = re.compile(r"['’ʼ`]")
_PUNCT = re.compile(r"[^\w\s]")
_WS = re.compile(r"\s+")


def normalise(s: str) -> str:
    """Case/punctuation/possessive/plural-insensitive form.

    NFKD first so composed and decomposed accents collapse; the apostrophe classes above are
    handled explicitly because NFKD does NOT fold U+2019 onto U+0027. Greenhouse renders
    "Bachelor’s Degree" with the curly one and a human types the straight one — different
    codepoints, and without this a free question escalates to a paid rung on punctuation.
    """
    s = unicodedata.normalize("NFKD", (s or "").strip().lower())
    s = _APOS.sub("", s)
    s = _PUNCT.sub(" ", s)
    s = _WS.sub(" ", s).strip()
    # Cheap singularisation: "degrees" == "degree". Deliberately not a stemmer — a stemmer
    # would also collapse things that mean different things, and a wrong match here is a
    # wrong answer on someone's job application.
    return " ".join(w[:-1] if len(w) > 3 and w.endswith("s") and not w.endswith("ss") else w
                    for w in s.split())


# --- the polarity guard -------------------------------------------------------------
#: Negations that can flip what "Yes" means. Word-bounded: "not" must not fire on "note",
#: and "no" must not fire on "north" (or on the OPTION "No", which is why this is only ever
#: run against the QUESTION text).
_NEGATION = re.compile(
    r"\b(not|never|no|nor|without|neither|non|didn'?t|haven'?t|hasn'?t|won'?t|"
    r"cannot|can'?t|isn'?t|aren'?t|wasn'?t|weren'?t)\b", re.I)

_YES_NO = {"yes", "no"}


def _is_yes_no(options: tuple[str, ...]) -> bool:
    return bool(options) and {normalise(o) for o in options} <= _YES_NO


def polarity_risk(question_text: str, options: tuple[str, ...]) -> tuple[bool, str]:
    """Could matching the options without reading the question invert the answer?

    Two triggers, both narrow on purpose — a false positive costs one operator question,
    while a false negative costs a wrong answer on a real application:

    1. A known-inverting field. `is_ai_use_attestation` already exists for exactly this and
       was called by nothing; this is its first caller.
    2. A Yes/No question containing a negation. "Are you authorized?" and "Are you NOT
       authorized?" offer identical options and take opposite answers. Restricted to Yes/No
       because with real option text ("Bachelor's Degree") the option itself carries the
       meaning, and a stray "not" in the question does not flip it.
    """
    q = (question_text or "").strip()
    if not q:
        return False, ""
    if is_ai_use_attestation(q):
        return True, ("AI-use attestation: the wording varies per employer and INVERTS "
                      "(KKR: 'confirm materials were NOT generated by AI' -> Yes = confirming; "
                      "elsewhere 'did you use AI?' -> Yes = admitting)")
    if _is_yes_no(options) and _NEGATION.search(q):
        m = _NEGATION.search(q)
        return True, (f"Yes/No question containing a negation ({m.group(0)!r}) — 'Yes' means "
                      f"the opposite of what it means without it")
    return False, ""


# --- the cascade --------------------------------------------------------------------
def resolve_answer(
    *,
    question_text: str,
    options: list[str] | tuple[str, ...],
    canonical_answer: str,
    ats: Optional[str] = None,
    field: Optional[str] = None,
    model: Optional[Reasoner] = None,
) -> Resolution:
    """Canonical answer -> the word THIS widget uses. Cheapest rung that can answer wins.

    Returns a `Resolution`; `needs_human=True` means ask the operator and then write the
    answer back into the alias table (rung 3), so each hard question is paid for once.
    """
    opts = tuple(o for o in (options or []) if o is not None)
    canonical = (canonical_answer or "").strip()
    if not canonical:
        return Resolution(None, 0.0, "none", "no canonical answer to translate", True)

    risky, why = polarity_risk(question_text, opts)

    # THE GUARD. Rungs 1-3 read only the OPTIONS, so on an inverted question they do not
    # miss — they hit and are silently wrong. Skip straight to a reasoner.
    if not risky:
        for opt in opts:
            if opt.strip() == canonical:
                return Resolution(opt, 1.0, "exact", f"{canonical!r} is offered verbatim", False)

        n_canonical = normalise(canonical)
        for opt in opts:
            if normalise(opt) == n_canonical:
                return Resolution(opt, 1.0, "normalised",
                                  f"{canonical!r} == {opt!r} after case/punct/plural normalisation",
                                  False)

        alias = _alias_for(ats, field, canonical)
        if alias is not None:
            for opt in opts:
                if normalise(opt) == normalise(alias):
                    return Resolution(opt, 1.0, "alias",
                                      f"recipe alias {canonical!r} -> {alias!r} (apply_fields)", False)
            # The alias table is stale: it names a word this widget does not offer. Say so —
            # a silent fallthrough to the model would hide a recipe that needs fixing.
            why = (f"recipe alias maps {canonical!r} -> {alias!r}, which is NOT among the "
                   f"offered options — the alias is stale")
        elif not opts:
            return Resolution(None, 0.0, "none", "the widget offered no options to choose from", True)
        else:
            why = f"{canonical!r} does not match any offered option exactly, normalised, or by alias"

    # Rung 4 — the seam. No model => rung 5, honestly.
    q = SemanticQuestion(question_text=question_text or "", options=opts,
                         canonical_answer=canonical, ats=ats, field=field,
                         polarity_risk=risky, why=why)
    if model is None:
        return Resolution(None, 0.0, "none",
                          f"{why}. No reasoner wired — ask the operator, then write the answer "
                          f"back into the alias table so it is free next time.", True)

    answer = model(q)
    if answer is None or answer.value is None:
        return Resolution(None, 0.0, "none",
                          f"{why}. The reasoner answered NONE"
                          + (f": {answer.rationale}" if answer and answer.rationale else "")
                          + " — ask the operator. Never invent application content.", True)
    if answer.value not in opts:
        # A reasoner that returns a word the widget does not offer has hallucinated. Refuse
        # it here rather than let /select_option discover it as a no_option three layers down.
        return Resolution(None, 0.0, "none",
                          f"the reasoner returned {answer.value!r}, which is not among the "
                          f"offered options {list(opts)} — refusing to guess", True)
    if answer.confidence < CONFIDENCE_THRESHOLD:
        return Resolution(answer.value, answer.confidence, "model",
                          f"{answer.rationale} (confidence {answer.confidence:.2f} < "
                          f"{CONFIDENCE_THRESHOLD} — ask, don't guess)", True)
    return Resolution(answer.value, answer.confidence, "model", answer.rationale, False)


def _alias_for(ats: Optional[str], field: Optional[str], canonical: str) -> Optional[str]:
    """The recipe's vocabulary for this field: canonical -> this widget's word.

    Lives in `apply_fields` (operator-editable data), not here (mechanism) — a lesson that
    lands in an endpoint's code instead of the recipe stops generalizing.
    """
    if not ats or not field:
        return None
    try:
        vocab = apply_fields.resolve(ats, field).get("vocabulary") or {}
    except apply_fields.FieldNotFound:
        return None
    if canonical in vocab:
        return vocab[canonical]
    n = normalise(canonical)
    return next((v for k, v in vocab.items() if normalise(k) == n), None)
