"""The semantic cascade's invariants.

The polarity tests are the ones that matter. Everything else is matching; those are the
cases where matching is confidently, silently wrong — and they are the reason a model has a
seam here at all.
"""

from __future__ import annotations

import pytest

from resolve_answer import (
    CONFIDENCE_THRESHOLD,
    ModelAnswer,
    Resolution,
    SemanticQuestion,
    normalise,
    polarity_risk,
    resolve_answer,
)

YES_NO = ["Yes", "No"]


def _reasoner(value, confidence=1.0, rationale="because"):
    seen = []

    def fn(q: SemanticQuestion):
        seen.append(q)
        return ModelAnswer(value=value, confidence=confidence, rationale=rationale)
    fn.seen = seen
    return fn


# --- the free rungs -----------------------------------------------------------------
def test_rung1_exact():
    r = resolve_answer(question_text="Phone device type", options=["Mobile", "Home"],
                       canonical_answer="Mobile")
    assert r.ok and r.value == "Mobile" and r.method == "exact"


def test_rung2_normalised_collapses_the_curly_apostrophe():
    """Greenhouse renders "Bachelor’s Degree" (U+2019); a human types "Bachelor's".

    Different codepoints. Without NFKD this is a MISS that escalates a free question to a
    paid rung — the cascade leaking money on punctuation.
    """
    r = resolve_answer(question_text="Degree", options=["Bachelor’s Degree", "Master’s Degree"],
                       canonical_answer="Bachelor's Degree")
    assert r.ok and r.value == "Bachelor’s Degree" and r.method == "normalised"


def test_rung2_normalises_case_punctuation_and_plurals():
    assert normalise("Bachelor's Degree") == normalise("bachelors degree")
    assert normalise("Kinesiology") == normalise("KINESIOLOGY")


def test_rung2_does_not_over_stem():
    # A stemmer would collapse words that mean different things, and a wrong match here is a
    # wrong answer on someone's application. "ss" endings must survive.
    assert normalise("Business") != normalise("Busine")
    assert normalise("Business") == "business"


def test_rung3_alias_comes_from_the_recipe_not_this_module():
    # Sports Science -> Kinesiology lives in apply_fields (operator-editable data). The
    # operator volunteered that mapping unprompted — the alias table asking to exist.
    r = resolve_answer(question_text="Discipline", options=["Kinesiology", "Biology"],
                       canonical_answer="Sports Science", ats="greenhouse", field="discipline")
    assert r.ok and r.value == "Kinesiology" and r.method == "alias"


def test_rung3_alias_maps_an_absent_school_to_Other():
    # UST is genuinely not in Greenhouse's list (verified: Ateneo de Manila IS).
    r = resolve_answer(question_text="School", options=["Other", "Ateneo de Manila University"],
                       canonical_answer="University of Santo Tomas",
                       ats="greenhouse", field="school")
    assert r.ok and r.value == "Other" and r.method == "alias"


def test_a_stale_alias_says_so_instead_of_silently_falling_through():
    # The alias names a word this widget doesn't offer => the recipe needs fixing, and the
    # rationale must say that rather than blaming the question.
    r = resolve_answer(question_text="Discipline", options=["Biology", "Chemistry"],
                       canonical_answer="Sports Science", ats="greenhouse", field="discipline")
    assert not r.ok and r.needs_human
    assert "stale" in r.rationale


# --- THE POLARITY GUARD -------------------------------------------------------------
def test_an_inverted_question_does_NOT_get_answered_by_exact_match():
    """The whole reason this module exists.

    store: ai_use_attestation = "Yes". Options: ["Yes", "No"]. An exact match on "Yes"
    SUCCEEDS — confidently — and is silently wrong when the question's polarity inverts.
    The free rungs never read the question, so they cannot know. They must not run.
    """
    r = resolve_answer(
        question_text="I confirm that my application materials were NOT generated by AI tools.",
        options=YES_NO, canonical_answer="Yes")
    assert r.value is None, "exact-matched 'Yes' on an inverted question — the silent inversion"
    assert r.needs_human and r.method == "none"
    assert "invert" in r.rationale.lower() or "attestation" in r.rationale.lower()


def test_polarity_risk_fires_on_the_ai_attestation_in_either_wording():
    for q in ["I confirm my materials were not generated or edited by AI tools (ChatGPT, Claude)",
              "Did you use AI tools such as ChatGPT to generate any part of this application?"]:
        risky, why = polarity_risk(q, tuple(YES_NO))
        assert risky, q
        assert why


def test_polarity_risk_fires_on_a_negated_yes_no_question():
    risky, why = polarity_risk("Are you NOT legally authorized to work in the U.S.?", tuple(YES_NO))
    assert risky and "negation" in why


def test_polarity_risk_does_NOT_fire_on_an_ordinary_yes_no_question():
    # A false positive costs one operator question; being trigger-happy would escalate the
    # whole form. These are the real KKR questions.
    for q in ["Are you legally authorized to work for our company in the U.S.?",
              "Will you now or in the future require visa sponsorship to work in the U.S.?",
              "Were you referred by a current or previous KKR employee?"]:
        risky, _ = polarity_risk(q, tuple(YES_NO))
        assert not risky, q


def test_negation_matching_is_word_bounded():
    # "not" must not fire on "note"; "no" must not fire on "north".
    for q in ["Please note your start date preference. Available?",
              "Are you willing to relocate to North Carolina?"]:
        risky, _ = polarity_risk(q, tuple(YES_NO))
        assert not risky, q


def test_polarity_risk_is_restricted_to_yes_no_options():
    # With real option text the OPTION carries the meaning, so a stray "not" in the question
    # doesn't flip it — escalating here would be noise.
    risky, _ = polarity_risk("Which degree did you not complete?",
                             ("Bachelor's Degree", "Master's Degree"))
    assert not risky


def test_an_inverted_question_reaches_the_reasoner_with_the_question_text():
    """The seam's contract: rungs 1-3 read only OPTIONS; the reasoner gets the QUESTION.

    That asymmetry is the point — the information needed to answer an inverted question is
    in the question, which is exactly what the cheap rungs cannot see.
    """
    fn = _reasoner("Yes", 0.95, "the question asks to CONFIRM no AI was used; the store says Yes")
    r = resolve_answer(
        question_text="I confirm that my materials were NOT generated by AI.",
        options=YES_NO, canonical_answer="Yes", model=fn)
    assert r.ok and r.value == "Yes" and r.method == "model"
    (q,) = fn.seen
    assert q.polarity_risk is True
    assert "NOT generated by AI" in q.question_text
    assert q.options == ("Yes", "No") and q.canonical_answer == "Yes"
    assert q.why


# --- rung 4/5: the seam ------------------------------------------------------------
def test_no_reasoner_wired_means_ask_the_operator_not_guess():
    r = resolve_answer(question_text="Discipline", options=["Astrophysics"],
                       canonical_answer="Kinesiology")
    assert not r.ok and r.needs_human and r.method == "none"
    assert "ask the operator" in r.rationale


def test_a_reasoner_answering_NONE_escalates_and_does_not_invent():
    fn = _reasoner(None, rationale="no offered option means Kinesiology")
    r = resolve_answer(question_text="Discipline", options=["Astrophysics"],
                       canonical_answer="Kinesiology", model=fn)
    assert not r.ok and r.needs_human
    assert "NONE" in r.rationale


def test_a_hallucinated_option_is_refused_at_this_layer():
    # A reasoner returning a word the widget doesn't offer must be caught here, not
    # discovered by /select_option as a no_option three layers down.
    fn = _reasoner("Kinesiology", 1.0)
    r = resolve_answer(question_text="Discipline", options=["Astrophysics", "Biology"],
                       canonical_answer="Sports Science", model=fn)
    assert not r.ok and r.needs_human
    assert "not among the offered options" in r.rationale


def test_low_confidence_asks_rather_than_guesses():
    fn = _reasoner("Biology", CONFIDENCE_THRESHOLD - 0.01, "vaguely similar")
    r = resolve_answer(question_text="Discipline", options=["Biology"],
                       canonical_answer="Sports Science", model=fn)
    assert r.value == "Biology" and r.needs_human    # surfaced, but gated
    assert not r.ok
    assert "ask, don't guess" in r.rationale


def test_the_reasoner_is_not_called_when_a_free_rung_answers():
    fn = _reasoner("Mobile")
    r = resolve_answer(question_text="Phone device type", options=["Mobile"],
                       canonical_answer="Mobile", model=fn)
    assert r.method == "exact" and fn.seen == [], "paid for a rung the cascade already answered"


def test_no_canonical_answer_is_not_a_question_for_the_model():
    r = resolve_answer(question_text="Degree", options=["Bachelor's"], canonical_answer="")
    assert not r.ok and r.needs_human and "no canonical answer" in r.rationale


def test_a_widget_offering_no_options_escalates():
    r = resolve_answer(question_text="Degree", options=[], canonical_answer="Bachelor's")
    assert not r.ok and r.needs_human
